# Changing this file necessitates a server restart
name: "Journal of Open Source Education"
abbreviation: "JOSE"
issn: "2577-3569"
tagline: "an <strong>educator friendly</strong> journal for publishing open-source educational materials and software."
logo_url: "http://jose.theoj.org/logo_large.png"
url: "https://jose.theoj.org"
editor_email: "jose.theoj@gmail.com"
noreply_email: "noreply@jose.theoj.org"
twitter: "@JOSE_TheOJ"
mastodon_url:
google_analytics: "UA-47852178-6"
github: "openjournals/jose"
reviews: "openjournals/jose-reviews"
papers_html_url: "https://www.theoj.org/jose-papers"
reviewers_signup_url: "https://jose.theoj.org/reviewer-signup.html"
papers_repo: "openjournals/jose-papers"
product: "software" # the *thing* being submitted for review
reviewers: "https://bit.ly/jose-reviewers"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your educational materials or software, and any questions you have about the JOSE submission criteria.
paper_types: ['software', 'learning module']
bot_username: editorialbot
