# Changing this file necessitates a server restart
name: "Journal of Open Source Education"
abbreviation: "JOSE"
issn: "2577-3569"
tagline: "an <strong>educator friendly</strong> journal for publishing open-source educational materials and software."
logo_url: "http://jose.theoj.org/logo_large.png"
url: "https://jose.theoj.org"
editor_email: "jose.theoj@gmail.com"
noreply_email: "admin@theoj.org"
launch_date: "2018-03-07"
twitter: "@JOSE_TheOJ"
mastodon_url:
google_analytics: "UA-47852178-6"
github: "openjournals/jose"
reviews: "openjournals/jose-reviews"
papers_repo: "openjournals/jose-papers"
papers_html_url: "https://www.theoj.org/jose-papers"
reviewers_url: "https://bit.ly/jose-reviewers"
reviewers_signup_url: "https://jose.theoj.org/reviewer-signup.html"
reviewers_lookup_url: "https://bit.ly/jose-reviewers"
product: "software" # the *thing* being submitted for review
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your educational materials or software, and any questions you have about the JOSE submission criteria.
paper_types: ['software', 'learning module']
bot_username: editorialbot
features:
  tracks: false
