# Changing this file necessitates a server restart
name: "Proceedings of the JuliaCon Conferences"
abbreviation: "JCON"
issn: "2642-4029"
tagline: "an open-access journal published in cooperation with the <a href='http://www.theoj.org/'>the Open Journals</a>."
logo_url: "http://proceedings.juliacon.org/logo_large.jpg"
url: "https://proceedings.juliacon.org"
editor_email: "admin@theoj.org"
noreply_email: "noreply@proceedings.juliacon.org"
twitter: "@juliaconorg"
google_analytics: "UA-47852178-9"
github: "openjournals/joss"
reviews: "openjournals/jcon-reviews"
papers_html_url: "https://www.theoj.org/joss-papers"
papers_repo: "openjournals/jcon-papers"
product: "software" # the *thing* being submitted for review
reviewers: "https://bit.ly/jcon-reviewers"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the JulianCon submission criteria.
paper_types: []
